apiVersion: v1     
kind: Pod           
                    
metadata:          
  name: webserver14
spec:              
  containers:
    - name: webserver14
      image: nginx:latest
      ports:
        - containerPort: 80