apiVersion: v1     
kind: Pod           
                    
metadata:          
  name: webserver4
spec:              
  containers:
    - name: webserver4
      image: nginx:latest
      ports:
        - containerPort: 80