apiVersion: v1     
kind: Pod           
                    
metadata:          
  name: webserver13
spec:              
  containers:
    - name: webserver13
      image: nginx:latest
      ports:
        - containerPort: 80