apiVersion: v1     
kind: Pod           
                    
metadata:          
  name: webserver3 
spec:              
  containers:
    - name: webserver3
      image: nginx:latest
      ports:
        - containerPort: 80